<?php

namespace App\Constants;

class TransactionActivityConstants
{

    const CREDIT_PROVIDER_USER = "CREDIT_PROVIDER_USER";
    const PROVIDER = "PROVIDER";
    const CURRENCY_EXCHANGE = "CURRENCY_EXCHANGE";
    const FUND_WITH_FLUTTERWAVE = "FUND_WITH_FLUTTERWAVE";
    const FUND_WITH_PAYPAL = "FUND_WITH_PAYPAL";
    const REFERRAL_BONUS = "REFERRAL_BONUS";
    const SIGNUP_BONUS = "SIGNUP_BONUS";
    const dashboard_BONUS = "dashboard_BONUS";
    const PROMOTION_COSTS = "PROMOTION_COSTS";
    const RUNNING_COSTS = "RUNNING_COSTS";

    const SUBSCRIBE_TO_MEMBERSHIP_PLAN = "SUBSCRIBE_TO_MEMBERSHIP_PLAN";
    const DAILY_NOTCH_BONUS = "DAILY_NOTCH_BONUS";

    const dashboard_FILTER_OPTIONS = [
        self::CREDIT_PROVIDER_USER => "CREDIT PROVIDER USER",
        self::PROVIDER => "PROVIDER",
        self::CURRENCY_EXCHANGE => "CURRENCY EXCHANGE",
        self::FUND_WITH_FLUTTERWAVE => "FUND WITH FLUTTERWAVE",
        self::REFERRAL_BONUS => "REFERRAL BONUS",
        self::SIGNUP_BONUS => "SIGNUP BONUS",
    ];
}
